# Generated by Django 5.0.6 on 2024-05-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('created_at',)},
        ),
    ]
