# Generated by Django 5.0.6 on 2024-05-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_roommembership_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='_content',
            field=models.TextField(db_column='content', default=''),
        ),
    ]
