# Generated by Django 5.0.6 on 2024-05-22 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_members_room_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(through='chat.RoomMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
